// AUTO-GENERATED by scripts/scan-avatars.mjs — do not edit by hand.
// To add a photo: drop an image into public/avatars/ named after the
// entry's slug (see public/avatars/README.md), then commit and push.
export const PHOTOS: Record<string, string> = {};
