// Scans public/avatars/ for real photos and writes data/photoManifest.ts.
// Runs automatically before `npm run dev` and `npm run build`.
//
// Drop an image into public/avatars/ named after an entry's slug
// (e.g. berkshire.jpg, nancy-pelosi.png) and it is picked up on the
// next build — no code changes needed.

import { readdirSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const avatarsDir = join(root, "public", "avatars");
const manifestPath = join(root, "data", "photoManifest.ts");

if (!existsSync(avatarsDir)) mkdirSync(avatarsDir, { recursive: true });

const IMAGE_RE = /\.(jpe?g|png|webp|gif|avif)$/i;
const files = readdirSync(avatarsDir).filter((f) => IMAGE_RE.test(f));

const map = {};
for (const file of files) {
  const slug = file.replace(/\.[^.]+$/, "").trim().toLowerCase();
  map[slug] = `/avatars/${file}`;
}

const body = `// AUTO-GENERATED by scripts/scan-avatars.mjs — do not edit by hand.
// To add a photo: drop an image into public/avatars/ named after the
// entry's slug (see public/avatars/README.md), then commit and push.
export const PHOTOS: Record<string, string> = ${JSON.stringify(map, null, 2)};
`;

writeFileSync(manifestPath, body);
console.log(
  `scan-avatars: ${files.length} photo(s) found in public/avatars/`
);
